version: '3'

services:
  gdapplib-manager:
    build:
      context: ./app
      dockerfile: ./Dockerfile.native-micro
    image: "gdshell/gdapplib-manager:latest"
    mem_limit: 128m
    container_name: gdapplib-manager
    env_file:
      - .env
    depends_on:
      gdapplib-db:
        condition: service_healthy
    networks:
      - gdapplib-server

  gdapplib-db:
    build:
      context: ./db
      dockerfile: ./Dockerfile.db
    image: "gdshell/gdapplib-db:latest"
    mem_limit: 128m
    container_name: gdapplib-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - gdapplib-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    networks:
      - gdapplib-server

networks:
  gdapplib-server:
    driver: bridge

volumes:
  gdapplib-db: