version: '3.9'

services:
  gdapplib-manager:
    build:
      context: ./app
      dockerfile: ./src/main/docker/Dockerfile.native-micro
      args:
        - JAVA_OPTS=-Duser.home=/home
    image: "fenixhub/gdapplib-manager:latest"
    mem_limit: 128m
    container_name: gdapplib-manager
    env_file:
      - .env
    depends_on:
      gdapplib-db:
        condition: service_healthy
    ports:
      - 8081:8080
    networks:
      - gdapplib-server
    volumes:
      - archives:/home/gdapplib

  gdapplib-db:
    build:
      context: ./db
      dockerfile: ./docker/Dockerfile.db
    image: "fenixhub/gdapplib-db:latest"
    mem_limit: 128m
    container_name: gdapplib-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - 5432:5432
    networks:
      - gdapplib-server

networks:
  gdapplib-server:
    name: gdapplib-server
    driver: bridge

volumes:
  db:
  archives:
